# Generated by Django 4.2.5 on 2023-09-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allow_original_link', models.BooleanField(default=False)),
                ('allow_expiring_link', models.BooleanField(default=False)),
                ('thumbnail_sizes', models.CharField(help_text="Comma-separated list of thumbnail sizes (e.g., '200x200,400x400')", max_length=255)),
                ('expiring_link_seconds', models.PositiveIntegerField(help_text='Expiring link duration in seconds (between 300 and 30000)')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='expiring_link_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Expiring link duration in seconds (between 300 and 30000)', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_sizes',
            field=models.CharField(help_text="Comma-separated list of thumbnail sizes (e.g., '200x200,400x400')", max_length=255),
        ),
    ]
