# Generated by Django 4.2.5 on 2023-09-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customtier_alter_image_expiring_link_seconds_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTier',
        ),
    ]
