# Generated by Django 4.2.5 on 2023-09-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_customtier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_sizes', models.CharField(help_text="Comma-separated list of thumbnail sizes (e.g., '200x200,400x400')", max_length=255)),
                ('allow_original_link', models.BooleanField()),
                ('allow_expiring_link', models.BooleanField()),
                ('expiring_link_seconds', models.PositiveIntegerField(help_text='Expiring link duration in seconds (between 300 and 30000)')),
            ],
        ),
    ]
