# Generated by Django 4.2.5 on 2023-09-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customtier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtier',
            name='allow_expiring_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtier',
            name='allow_original_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtier',
            name='expiring_link_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Expiring link duration in seconds (between 300 and 30000)'),
        ),
    ]
