# Generated by Django 4.2.5 on 2023-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customtier_allow_expiring_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtier',
            name='expiring_link_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Expiring link duration in seconds (between 300 and 30000)', null=True),
        ),
    ]
