# Generated by Django 4.2.5 on 2023-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customtier_expiring_link_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='basic_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='enterprise_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='premium_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtier',
            name='allow_expiring_link',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customtier',
            name='allow_original_link',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customtier',
            name='expiring_link_seconds',
            field=models.PositiveIntegerField(help_text='Expiring link duration in seconds (between 300 and 30000)'),
        ),
    ]
