# Generated by Django 4.2.5 on 2023-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image_basic_link_image_enterprise_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='enterprise_link',
        ),
        migrations.AddField(
            model_name='image',
            name='expiring_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='original_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='basic_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='premium_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
