# Generated by Django 4.2.5 on 2023-09-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_image_enterprise_link_image_expiring_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='basic_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='expiring_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='premium_link',
        ),
    ]
