# Generated by Django 4.2.5 on 2023-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_image_basic_link_remove_image_expiring_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTier',
        ),
        migrations.AlterField(
            model_name='tier',
            name='allow_expiring_link',
            field=models.BooleanField(help_text='Allow ability to generate expiring links'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='allow_original_link',
            field=models.BooleanField(help_text='Allow presence of the link to the originally uploaded file'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_sizes',
            field=models.BooleanField(help_text='Allow arbitrary thumbnail sizes'),
        ),
    ]
