# Generated by Django 4.2.5 on 2023-09-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_customtier_alter_tier_allow_expiring_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='arbitrary_thumbnail_size',
            field=models.PositiveIntegerField(blank=True, help_text='Expiring link duration in seconds (between 300 and 30000)', null=True),
        ),
    ]
